# Generated by Django 3.1a1 on 2020-05-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200516_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='languate',
            new_name='language',
        ),
    ]
