# Generated by Django 3.1a1 on 2020-05-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='aminity',
            new_name='aminities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='houserule',
            new_name='house_rules',
        ),
    ]
